apiVersion: v1
kind: Pod
metadata:
  name: cup-load-test-pod
  namespace: test
spec:
  containers:
    - name: cup-load-test-pod
      image: nuc.lliu.ca/lliu/scale_maker:28
      command:
        - /usr/bin/bash
        - -c
        - sleep 9999999999999999999999999
      livenessProbe:
        exec:
          command:
          - /bin/true
      readinessProbe:
        exec:
          command:
          - /bin/true
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
      securityContext: {}