info:
  contact: {}
paths:
  /api/v1/daemonset/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the Daemonsets in the k8s cluster.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Gets the list of the Daemonsets in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/ping:
    get:
      consumes:
      - application/json
      description: Fetch the current status of the application.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: {\"status\":\"alive\"}'
      summary: Fetch the current status of the application.
      tags:
      - Status
swagger: "2.0"
