info:
  contact: {}
paths:
  /api/v1/bulk/create:
    post:
      consumes:
      - application/yaml
      description: Creates all the resources passed via request body.
      parameters:
      - description: body_param
        in: body
        name: body_param
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Creates all the resources passed via request body.
      tags:
      - Kubernetes Bulk API
  /api/v1/daemonset/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the daemonsets in the k8s cluster.
      parameters:
      - description: daemonset search by namespace
        format: string
        in: query
        name: namespace
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Gets the list of the Daemonsets in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/deployment/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the deployments in the k8s cluster.
      parameters:
      - description: deployment search by namespace
        format: string
        in: query
        name: namespace
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"deployments\":[],\"namespace\":\"default\",\"number_of_deployments\":0,\"status\":200}'
      summary: Gets the list of the deployments in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/namespace/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the namespaces in the k8s cluster.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"namespaces\":[],\"number_of_namespaces\":0,\"status\":200}'
      summary: Gets the list of the namespaces in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/node/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the nodes in the k8s cluster.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Gets the list of the nodes in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/ping:
    get:
      consumes:
      - application/json
      description: Fetch the current status of the application.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: {\"status\":\"alive\"}'
      summary: Fetch the current status of the application.
      tags:
      - Status
  /api/v1/pod/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the pods in the k8s cluster.
      parameters:
      - description: pod search by namespace
        format: string
        in: query
        name: namespace
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"namespace\":\"default\",\"number_of_pods\":0,\"pods\":[],\"status\":200}'
      summary: Gets the list of the pods in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/pod/template/create:
    post:
      consumes:
      - application/yaml
      description: Creates the pods from the pod template, currently the method only
        supports pod with one container.
      parameters:
      - description: namespace to create the pod
        format: string
        in: query
        name: namespace
        type: string
      - description: template name needed to create the pod
        format: string
        in: query
        name: template_name
        type: string
      - description: requested cpu value
        format: string
        in: query
        name: cpu_request
        type: string
      - description: requested memory value
        format: string
        in: query
        name: memory_request
        type: string
      - description: limited cpu value
        format: string
        in: query
        name: cpu_limit
        type: string
      - description: limited memory value
        format: string
        in: query
        name: memory_limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"message\":\"pod has been created successfully\",\"status\":200}'
      summary: Creates the pods from the pod template.
      tags:
      - Kubernetes
  /api/v1/pod/yaml/create:
    post:
      consumes:
      - application/yaml
      description: Creates the pods from the request body.
      parameters:
      - description: body_param
        in: body
        name: body_param
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"message\":\"pod has been created successfully\",\"status\":200}'
      summary: Creates the pods from the request body.
      tags:
      - Kubernetes
  /api/v1/service/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the services in the k8s cluster.
      parameters:
      - description: service search by namespace
        format: string
        in: query
        name: namespace
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"namespace\":\"default\",\"number_of_services\":0,\"services\":[],\"status\":200}'
      summary: Gets the list of the services in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/statefulset/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the statefulsets in the k8s cluster.
      parameters:
      - description: statefulset search by namespace
        format: string
        in: query
        name: namespace
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"namespace\":\"default\",\"number_of_statefulsets\":0,\"statefulsets\":[],\"status\":200}'
      summary: Gets the list of the statefulsets in the k8s cluster.
      tags:
      - Kubernetes
swagger: "2.0"
