info:
  contact: {}
paths:
  /api/v1/bulk/create:
    post:
      consumes:
      - application/json
      description: Creates all the resources passed via request body.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Creates all the resources passed via request body.
      tags:
      - Bulk Kubernetes
  /api/v1/daemonset/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the daemonsets in the k8s cluster.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Gets the list of the Daemonsets in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/deployment/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the deployments in the k8s cluster.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Gets the list of the deployments in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/namespace/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the namespaces in the k8s cluster.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Gets the list of the namespaces in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/node/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the nodes in the k8s cluster.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Gets the list of the nodes in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/ping:
    get:
      consumes:
      - application/json
      description: Fetch the current status of the application.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: {\"status\":\"alive\"}'
      summary: Fetch the current status of the application.
      tags:
      - Status
  /api/v1/pod/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the pods in the k8s cluster.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Gets the list of the pods in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/pod/template/create:
    post:
      consumes:
      - application/json
      description: Creates the pods from the pod template.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Creates the pods from the pod template.
      tags:
      - Kubernetes
  /api/v1/pod/yaml/create:
    post:
      consumes:
      - application/json
      description: Creates the pods from the request body.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Creates the pods from the request body.
      tags:
      - Kubernetes
  /api/v1/service/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the services in the k8s cluster.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Gets the list of the services in the k8s cluster.
      tags:
      - Kubernetes
  /api/v1/statefulset/list:
    get:
      consumes:
      - application/json
      description: Gets the list of the statefulsets in the k8s cluster.
      produces:
      - application/json
      responses:
        "200":
          description: 'Sample result: "{\"daemonsets\":[],\"namespace\":\"default\",\"number_of_daemonsets\":0,\"status\":200}'
      summary: Gets the list of the statefulsets in the k8s cluster.
      tags:
      - Kubernetes
swagger: "2.0"
